### ISSUE TITLE
Display progress while running automatic tests

### ISSUE THREAD

**Issue by rowan-m** [valorin/samesite#1]
The suite takes quite a while to run and the names are all quite similar, so at some points it looked as if tests were being repeated. Something simple like "Test 1/42" or similar in the heading would make this clearer. Alternatively, get fancy and add an actual progress bar.

**Comment by valorin** [comment]
Ah yes, good point. I can see how that would be quite confusing. A progress bar would definitely be a nice touch. Thanks for the suggestion! :-)

**Comment by valorin** [comment]
Progress bar has been added! Thanks for the suggestion @rowan-m 👍
